# Generated by Django 5.2 on 2025-05-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valuation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('traction_item1', models.TextField(blank=True, null=True)),
                ('traction_item2', models.TextField(blank=True, null=True)),
                ('traction_item3', models.TextField(blank=True, null=True)),
                ('target_customer', models.TextField(blank=True, null=True)),
                ('team_member1_name', models.TextField(blank=True, null=True)),
                ('team_member1_title', models.TextField(blank=True, null=True)),
                ('team_member1_bio', models.TextField(blank=True, null=True)),
                ('team_member2_name', models.TextField(blank=True, null=True)),
                ('team_member2_title', models.TextField(blank=True, null=True)),
                ('team_member2_bio', models.TextField(blank=True, null=True)),
                ('market_size_description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('funding_usage', models.TextField(blank=True, null=True)),
                ('problem_description', models.TextField(blank=True, null=True)),
                ('solution_description', models.TextField(blank=True, null=True)),
                ('traction_description', models.TextField(blank=True, null=True)),
                ('documents', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_plans', to='companies.company')),
            ],
            options={
                'db_table': 'company_business_plan',
            },
        ),
    ]
