# Generated by Django 5.2 on 2025-05-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        ('companies', '0003_company_slide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFundraiseTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('equity', 'Equity'), ('convertible debt', 'Convertible Debt'), ('debt', 'Debt')], max_length=20)),
                ('raise_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('duration', models.CharField(default='Until Funded or Canceled', max_length=100)),
                ('pre_money_valuation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('previous_investments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valuation_cap_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('convertible_note_discount', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('max_investors', models.IntegerField(default=0)),
                ('min_investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_interest_rate', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('repayment_term', models.IntegerField(default=0)),
                ('funding_committed_offline', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fundraise_visibility', models.CharField(default='Private', max_length=20)),
                ('additional_terms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'db_table': 'company_fundraise_terms',
            },
        ),
    ]
